### ISSUE TITLE
No RSS/Atom feed for https://cppalliance.org/news?

### ISSUE THREAD

**Issue by bryceschober** [CPPAlliance/cppalliance.github.io#84]
How hard would it be to get an RSS/Atom feed?

**Comment by vinniefalco** [comment]
No idea. What is that?

**Comment by bryceschober** [comment]
Here's [the wikipedia article](https://en.wikipedia.org/wiki/Atom_(Web_standard))... for subscribing to blogs & such using tools like Feedly.com. The first search hits I get for Jekyll include options for [with](https://github.com/jekyll/jekyll-feed) and [without](https://jekyllcodex.org/without-plugin/rss-feed/#) a plugin.

**Comment by louistatta** [comment]
Thank you for the suggestion.
https://cppalliance.org/#news
